add solution for dz6-avatar
js-tasks-ru/htmlcss-20230227_veroncher pull request #11
Opened 2023-03-24 17:15 UTC by Veroncher

Герман! Сверстала аватар. Проверь, пожалуйста! =)

2023-03-24 17:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-24 17:41 UTC, GSemikozov requested changes

2023-03-24 17:41 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.img-wrap {
.avatar

2023-03-24 17:41 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.img-wrap img {
.avatar__img

2023-03-24 17:41 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.img-wrap img {
и border-radius: 50%

2023-03-24 17:47 UTC, Veroncher commented on 06-lection4/01-avatar/avatar.css
> +.img-wrap {
исправила

2023-03-24 17:47 UTC, Veroncher commented on 06-lection4/01-avatar/avatar.css
> +.img-wrap img {
исправила

2023-03-24 17:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-29 10:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-29 10:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-29 10:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-30 10:33 UTC, GSemikozov requested changes

2023-03-30 10:33 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__img img {
просто .avatar__img (класс который добавляем на img) =)

2023-03-31 16:42 UTC, GSemikozov requested changes

2023-04-04 20:03 UTC, merged