add solution for dz7-checkbox
js-tasks-ru/htmlcss-20230227_veroncher pull request #12
Opened 2023-03-30 18:01 UTC by Veroncher

Герман, сверстала чекбокс, проверь, пожалуйста.

2023-03-30 18:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-30 18:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-30 18:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-31 16:45 UTC, GSemikozov requested changes

2023-03-31 16:45 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__list {
тут сразу 2 ошибки:
1. элемент блока не может быть родителем самого блока (сын не может быть своим папой)
2. это обертка для блока, ее в этой файле стилей добавлять не надо, удалим

2023-03-31 16:45 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    cursor: default;
лучше pointer-events: none

2023-05-05 07:22 UTC, GSemikozov approved these changes

2023-05-05 07:22 UTC, merged