add solution for dz6-background-image
js-tasks-ru/htmlcss-20230227_veroncher pull request #17
Opened 2023-05-04 16:18 UTC by Veroncher

Герман, привет. И эту задачу проверь, пожалуйста)

2023-05-04 16:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-04 16:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-04 16:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-05 11:54 UTC, GSemikozov requested changes

2023-05-05 11:54 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width: 400px) {
поскольку mobile-first, то эта картинка будет стоять по умолчанию, не нужно здесь заворачивать в медиа-запрос

2023-05-17 15:49 UTC, GSemikozov requested changes

2023-05-17 15:49 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width: 400px) {
это медиа-запрос надо удалить)

2023-06-08 12:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-11 21:38 UTC, GSemikozov approved these changes

2023-06-11 21:38 UTC, merged