add solution for dz3-button
js-tasks-ru/htmlcss-20230227_veroncher pull request #5
Opened 2023-03-10 17:21 UTC by Veroncher

Герман, вроде бы сверстала кнопки.
Проверь, пожалуйста.

2023-03-10 17:25 UTC, GSemikozov requested changes

2023-03-10 17:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-10 17:59 UTC, Veroncher commented
Я сделала исправления. Проверь, пожалуйста, все ли я правильно поняла.

2023-03-11 10:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-11 10:18 UTC, Veroncher commented
Добавила padding  и исправила ошибки. Проверь, пожалуйста.

2023-03-11 11:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-15 00:58 UTC, GSemikozov requested changes

2023-03-15 00:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 40px;
`15px 40px 14px` ))

2023-03-15 00:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled,
disabled - состояние общее, поэтому - `.button:disabled { pointer-events: none; opacity: 0.5 }` - этого достаточно

2023-03-15 00:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_secondary:hover:disabled {
ну и ховева у disabled не должно быть

2023-03-16 10:21 UTC, Veroncher commented on 03-lection1/01-button/button.css
> +.button_secondary:hover:disabled {
Исправила.

2023-03-16 10:38 UTC, GSemikozov approved these changes

2023-03-16 10:38 UTC, merged