add solution for dz4-skeleton
js-tasks-ru/htmlcss-20230227_veroncher pull request #7
Opened 2023-03-13 12:17 UTC by Veroncher

Герман, привет! Сверстала скелетон. Проверь, пожалуйста.

2023-03-13 12:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-15 01:06 UTC, GSemikozov requested changes

2023-03-15 01:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
размеры не надо фиксировать

2023-03-15 01:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 24px 24px 0;
`24px 40px 32px 24px`

2023-03-15 01:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.top {
отсюда и ниже - почему-то перестали использовать БЭМ) просьба оформить все классы по БЭМ + имена элементам и модификаторам дать более осмысленные

2023-03-15 01:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
ширины у линий в процентах (можно приблизительно)

2023-03-15 01:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
и - реализовать через модификаторы

2023-03-17 10:10 UTC, Veroncher commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
Исправила

2023-03-17 10:10 UTC, Veroncher commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 24px 24px 0;
Исправила

2023-03-17 10:10 UTC, Veroncher commented on 04-lection2/02-skeleton/skeleton.css
> +.top {
Вроде все по БЭМ сделала сейчас =)

2023-03-17 10:11 UTC, Veroncher commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
И здесь, все сделала. =)

2023-03-17 15:35 UTC, GSemikozov requested changes

2023-03-17 15:35 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
ширину удалим

2023-03-17 15:35 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title-string:nth-child(2) {
.skeleton__line_small

2023-03-20 11:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-20 12:49 UTC, GSemikozov requested changes

2023-03-20 12:49 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line_small:nth-child(1) {
а если в дизайне поменяют короткую и длинную линию местами? придется еще и в css менять))
так что - для короткой линии лучше создать еще один модификатор, только тот что выше - .skeleton__line_middle, а этот - .skeleton__line_small. И - тогда именно такие значения нужны? судя по макету, там будет везде ширина больше 50% от родителя

2023-03-20 12:49 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line_small {
у модификатора указываем только то ЧТО модифицируем и другие свойства не дублируем = здесь только width

2023-03-20 12:49 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__line_small">
модификаторы всегда используются только с теми блоками / элементами, которые они модифицируют

2023-03-30 10:31 UTC, merged